name: Update data

on:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "tools"
  cancel-in-progress: false

jobs:
  get-data:
    runs-on: ubuntu-latest
    name: Update data
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Update data
        run: |
          bash bin/get_data.sh

      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 23.3.1-0   # <- specify a valid version
          environment-file: environment.yml
          activate-environment: microgalaxy_paper
          use-mamba: true
          auto-activate-base: false

      - name: Install CRAN-only R packages
        shell: bash -l {0}
        run: |
          R -q -e 'install.packages(c("ggstream"), repos="https://cloud.r-project.org")'

      - name: Build figures
        shell: bash -l {0}
        run: |
          bash /bin/build_figures.sh

      - name: Archive data
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: docs/supplementary/available_public_servers.csv

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update data
          title: Update data
          body: Update data from the codex
          base: main
          branch: update-data
          delete-branch: true
      
